const leadsList = [
    {
        name :"John Smith", // add different names
        phoneNumber : "+919963637282", // diff  numbers
        email : "abcyx@bmail.com", //same as above
        age:17,
        source : 'facebook', // options : facebook , google, linkedin, agent
        status : 'open', // open, close
        converted : false,
        type : 'Term Insurance', //true and false
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'linkedin',
        status : 'open',
        converted : false,
        age:45,
        type : 'Health Insurance',
        
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'google',
        status : 'open',
        converted : false,
        age:33,
        type : 'Term Insurance',
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'agent',
        status : 'open',
        converted : false,
        age:60,
        type : 'Car Insurance',
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'facebook',
        status : 'open',
        converted : false,
        age:29,
        type : 'Property Insurance',
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'facebook',
        age:16,
        status : 'closed',
        converted : true,
        type : 'Property Insurance',
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'facebook',
        status : 'closed',
        converted : false,
        type : 'Term Insurance',
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'facebook',
        status : 'open',
        age:21,
        converted : false,
        type : 'Term Insurance',
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'facebook',
        status : 'open',
        converted : false,
        age:31,
        type : 'Health Insurance',
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'google',
        status : 'open',
        converted : false,
        age:65,
        type : 'Health Insurance',
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'google',
        status : 'open',
        converted : false,
        age:52,
        type : 'Term Insurance',
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'facebook',
        status : 'open',
        converted : false,
        age:48,
        type : 'Term Insurance',
    },
    {
        name :"John Smith",
        phoneNumber : "+919963637282",
        email : "abcyx@bmail.com",
        source : 'facebook',
        status : 'open',
        converted : true,
        age:61,
        type : 'Car Insurance',
    },
]

export default leadsList
